/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#6f3800",
        "surface-container": "#edeeef",
        "error-container": "#ffdad6",
        "primary-container": "#a100ff",
        "surface": "#f8f9fa",
        "outline-variant": "#d1c1d8",
        "tertiary-container": "#a55700",
        "secondary": "#0060a8",
        "surface-tint": "#8e00e2",
        "tertiary-fixed": "#ffdcc4",
        "error": "#ba1a1a",
        "surface-dim": "#d9dadb",
        "secondary-container": "#58a6fe",
        "tertiary": "#814300",
        "on-surface": "#191c1d",
        "surface-container-high": "#e7e8e9",
        "on-secondary-fixed": "#001c38",
        "outline": "#807287",
        "on-tertiary-fixed": "#2f1500",
        "secondary-fixed": "#d3e4ff",
        "background": "#f8f9fa",
        "on-primary-fixed": "#2e004e",
        "on-secondary-fixed-variant": "#004881",
        "on-secondary-container": "#003b6a",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#6c00ae",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#f2daff",
        "tertiary-fixed-dim": "#ffb77f",
        "on-primary": "#ffffff",
        "primary": "#7e00c9",
        "surface-container-low": "#f3f4f5",
        "on-background": "#191c1d",
        "secondary-fixed-dim": "#a2c9ff",
        "surface-variant": "#e1e3e4",
        "surface-container-highest": "#e1e3e4",
        "on-error-container": "#93000a",
        "inverse-primary": "#e1b6ff",
        "primary-fixed-dim": "#e1b6ff",
        "inverse-on-surface": "#f0f1f2",
        "on-primary-container": "#f9e8ff",
        "on-surface-variant": "#4e4256",
        "inverse-surface": "#2e3132",
        "on-error": "#ffffff",
        "on-tertiary-container": "#ffeadc",
        "surface-bright": "#f8f9fa"
      },
      animation: {
        'shuffle': 'resume-shuffle 8s ease-in-out infinite',
        'sub-shuffle': 'sub-card-shuffle 8s ease-in-out infinite',
      },
      keyframes: {
        'resume-shuffle': {
          '0%, 100%': { transform: 'rotate(2deg) translateX(0)', zIndex: '10' },
          '25%': { transform: 'rotate(-2deg) translateX(-10px)', zIndex: '5' },
          '50%': { transform: 'rotate(0deg) translateY(10px)', zIndex: '5' },
          '75%': { transform: 'rotate(4deg) translateX(10px)', zIndex: '10' },
        },
        'sub-card-shuffle': {
          '0%, 100%': { transform: 'rotate(-6deg) translate(0, 0)' },
          '50%': { transform: 'rotate(-2deg) translate(-20px, -20px)' },
        }
      }
    },
  },
  plugins: [],
}